INSERT INTO
cards(name, value, image, ace)
VALUES
--Spades
    ('AS', 11, 'https://deckofcardsapi.com/static/img/AS.png', true),
    ('2S', 2, 'https://deckofcardsapi.com/static/img/2S.png', false ),
    ('3S', 3, 'https://deckofcardsapi.com/static/img/3S.png', false ),
    ('4S', 4, 'https://deckofcardsapi.com/static/img/4S.png', false ),
    ('5S', 5, 'https://deckofcardsapi.com/static/img/5S.png', false ),
    ('6S', 6, 'https://deckofcardsapi.com/static/img/6S.png', false ),
    ('7S', 7, 'https://deckofcardsapi.com/static/img/7S.png', false ),
    ('8S', 8, 'https://deckofcardsapi.com/static/img/8S.png', false ),
    ('9S', 9, 'https://deckofcardsapi.com/static/img/9S.png', false ),
    ('1S', 10, 'https://deckofcardsapi.com/static/img/0S.png', false ),
    ('JS', 10, 'https://deckofcardsapi.com/static/img/JS.png', false ),
    ('QS', 10, 'https://deckofcardsapi.com/static/img/QS.png', false ),
    ('KS', 10, 'https://deckofcardsapi.com/static/img/KS.png', false ),
--Clubs
    ('AC', 11, 'https://deckofcardsapi.com/static/img/AC.png', true),
    ('2C', 2, 'https://deckofcardsapi.com/static/img/2C.png', false ),
    ('3C', 3, 'https://deckofcardsapi.com/static/img/3C.png', false ),
    ('4C', 4, 'https://deckofcardsapi.com/static/img/4C.png', false ),
    ('5C', 5, 'https://deckofcardsapi.com/static/img/5C.png', false ),
    ('6C', 6, 'https://deckofcardsapi.com/static/img/6C.png', false ),
    ('7C', 7, 'https://deckofcardsapi.com/static/img/7C.png', false ),
    ('8C', 8, 'https://deckofcardsapi.com/static/img/8C.png', false ),
    ('9C', 9, 'https://deckofcardsapi.com/static/img/9C.png', false ),
    ('1C', 10, 'https://deckofcardsapi.com/static/img/0C.png', false ),
    ('JC', 10, 'https://deckofcardsapi.com/static/img/JC.png', false ),
    ('QC', 10, 'https://deckofcardsapi.com/static/img/QC.png', false ),
    ('KC', 10, 'https://deckofcardsapi.com/static/img/KC.png', false ),
--Hearts
    ('AH', 11, 'https://deckofcardsapi.com/static/img/AH.png', true),
    ('2H', 2, 'https://deckofcardsapi.com/static/img/2H.png', false ),
    ('3H', 3, 'https://deckofcardsapi.com/static/img/3H.png', false ),
    ('4H', 4, 'https://deckofcardsapi.com/static/img/4H.png', false ),
    ('5H', 5, 'https://deckofcardsapi.com/static/img/5H.png', false ),
    ('6H', 6, 'https://deckofcardsapi.com/static/img/6H.png', false ),
    ('7H', 7, 'https://deckofcardsapi.com/static/img/7H.png', false ),
    ('8H', 8, 'https://deckofcardsapi.com/static/img/8H.png', false ),
    ('9H', 9, 'https://deckofcardsapi.com/static/img/9H.png', false ),
    ('1H', 10, 'https://deckofcardsapi.com/static/img/0H.png', false ),
    ('JH', 10, 'https://deckofcardsapi.com/static/img/JH.png', false ),
    ('QH', 10, 'https://deckofcardsapi.com/static/img/QH.png', false ),
    ('KH', 10, 'https://deckofcardsapi.com/static/img/KH.png', false ),
--Diamonds
    ('AD', 11, 'https://deckofcardsapi.com/static/img/AD.png', true),
    ('2D', 2, 'https://deckofcardsapi.com/static/img/2D.png', false ),
    ('3D', 3, 'https://deckofcardsapi.com/static/img/3D.png', false ),
    ('4D', 4, 'https://deckofcardsapi.com/static/img/4D.png', false ),
    ('5D', 5, 'https://deckofcardsapi.com/static/img/5D.png', false ),
    ('6D', 6, 'https://deckofcardsapi.com/static/img/6D.png', false ),
    ('7D', 7, 'https://deckofcardsapi.com/static/img/7D.png', false ),
    ('8D', 8, 'https://deckofcardsapi.com/static/img/8D.png', false ),
    ('9D', 9, 'https://deckofcardsapi.com/static/img/9D.png', false ),
    ('1D', 10, 'https://deckofcardsapi.com/static/img/0D.png', false ),
    ('JD', 10, 'https://deckofcardsapi.com/static/img/JD.png', false ),
    ('QD', 10, 'https://deckofcardsapi.com/static/img/QD.png', false ),
    ('KD', 10, 'https://deckofcardsapi.com/static/img/KD.png', false )